# Nome do nosso workflow de automação
name: Monitorar Preços Diariamente

# =================================================================
# Gatilhos: QUANDO este workflow deve rodar?
# =================================================================
on:
  # Gatilho 1: Agendamento (schedule)
  # A sintaxe "cron" define o horário. "0 9 * * *" significa:
  # "Às 09:00, todos os dias". (Lembre-se que o horário é UTC, 3h a mais que Brasília)
  schedule:
    - cron: '0 12 * * *' # Executa ao meio-dia UTC (09:00 no Brasil)

  # Gatilho 2: Manual (workflow_dispatch)
  # Isso adiciona um botão "Run workflow" na aba Actions, para podermos testar a qualquer momento.
  workflow_dispatch:

# =================================================================
# Tarefas: O QUE este workflow deve fazer?
# =================================================================
jobs:
  # Nome da nossa única tarefa
  verificar-precos:
    # O tipo de máquina virtual que vai rodar nosso código
    runs-on: ubuntu-latest

    # Os passos que a máquina deve seguir
    steps:
      # Passo 1: "Baixar" uma cópia do nosso repositório para a máquina virtual
      - name: Clonar o repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar o ambiente Python
      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instalar as bibliotecas Python que nosso script precisa
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Passo 4: EXECUTAR NOSSO SCRIPT!
      - name: Executar o monitor de preços
        # Aqui passamos nossas senhas do cofre "Secrets" para o script
        env:
          MEU_TOKEN_TELEGRAM: ${{ secrets.MEU_TOKEN_TELEGRAM }}
          MEU_CHAT_ID_TELEGRAM: ${{ secrets.MEU_CHAT_ID_TELEGRAM }}
        run: python monitor_precos.py
